import { OverlayCustomization } from '../types';

export const defaultCustomization: OverlayCustomization = {
  updateIntervalMs: 1000,
  showHP: true,
  showAdrenaline: true,
  showPrayer: true,
  showSummoning: true,
  showText: true,
  showIcons: true,
  barHeight: 20,
  barWidth: 150,
  colors: {
    hp: '#ff4757',
    hpLow: '#ff3838',
    adrenaline: '#ffa502',
    prayer: '#5352ed',
    summoning: '#2ed573',
    background: 'rgba(0, 0, 0, 0.3)',
    border: 'rgba(255, 255, 255, 0.5)',
    text: '#ffffff',
  },
  opacity: 0.9,
  fontSize: 12,
  lowHpThreshold: 25,
  position: { x: 10, y: 10 },
  layout: 'horizontal',
  alwaysOnTop: true,
  hideWhenFull: false,
  theme: 'classic',
  themeLayout: { gap: 8, iconAreaWidth: 20, adrenalineFullWidth: true, order: ['hp', 'prayer', 'summoning', 'adrenaline'] },
  gradient: {
    orientation: 'horizontal',
    hp: { from: '#ff6b6b', to: '#ff1e42' },
    adrenaline: { from: '#ffce54', to: '#ffa502' },
    prayer: { from: '#748ffc', to: '#5352ed' },
    summoning: { from: '#51e3a4', to: '#2ed573' },
  },
  textPosition: 'inside',
  textAlign: 'center',
  overcapTextFormat: '{current}/{max}',
  overcapTextColor: '#ffffff',
  textShadow: true,
};
